{% set version = "1.2.0" %}

package:
  name: varlociraptor
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/varlociraptor/varlociraptor/archive/v{{ version }}.tar.gz
  sha256: 544addaa15220e4a27d25aef4f4090f5958184b41afc4e1da45e85335894a86a

requirements:
  build:
    - rust >=1.30
    - clangdev
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - gsl
    - openblas
    - libcblas
    - zlib
    - bzip2
    - xz
    - clangdev
    - blis
  run:
    - gsl
    - openblas
    - libcblas
    - zlib
    - bzip2
    - xz
    - blis

test:
  commands:
    - varlociraptor -h

about:
  home: https://varlociraptor.github.io
  license: GPLv3
  license_family: GPL
  summary: Flexible, uncertainty-aware variant calling with parameter free filtration via FDR control.
