package:
  name: r-eacon
  version: 0.3.4

source:
  url: https://github.com/gustaveroussy/EaCoN/archive/0.3.4.tar.gz
  sha256: cf11409c1e1c5c92672906b0e0417f9e4a35a8a84539605ca43547ba88ffa0c9

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-changepoint
    - r-bedr
    - r-data.table
    - r-devtools
    - r-dplyr
    - r-doparallel
    - r-dt
    - r-facets
    - r-foreach
    - r-iotools
    - r-matrixstats
    - r-mclust
    - r-rmarkdown
    - r-sequenza
    - bioconductor-affxparser
    - bioconductor-aroma.light
    - bioconductor-bsgenome
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-copynumber
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-limma
    - bioconductor-rhdf5
    - bioconductor-rsamtools
    - ascat
  run:
    - r-changepoint
    - r-bedr
    - r-data.table
    - r-devtools
    - r-dplyr
    - r-doparallel
    - r-dt
    - r-facets
    - r-foreach
    - r-iotools
    - r-matrixstats
    - r-mclust
    - r-rmarkdown
    - r-sequenza
    - bioconductor-affxparser
    - bioconductor-aroma.light
    - bioconductor-bsgenome
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-copynumber
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-limma
    - bioconductor-rhdf5
    - bioconductor-rsamtools
    - ascat

test:
  commands:
    - $R -e "library('EaCoN')"

about:
  home: https://github.com/gustaveroussy/EaCoN
  license: MIT
  summary: Easy Copy Number !
  license_family: MIT

extra:
  identifiers:
    - biotools:eacon

