on:
#  pull_request:
#    types: [ready_for_review]
  check_run:
    types: [completed]

jobs:
  report_artifacts:
    runs-on: ubuntu-latest
    name: Report Artifacts
    steps:
    - uses: actions/checkout@v1
    - name: debug
      run: env
